-- ============================================================
-- Magra School Management ERP V118 - Supabase Cloud Database Schema (Idempotent)
-- Run this script in your Supabase SQL Editor
-- ============================================================

-- 1. Create Teachers Table
CREATE TABLE IF NOT EXISTS public.teachers (
    id TEXT PRIMARY KEY,
    employee_id TEXT UNIQUE,
    name_bn TEXT NOT NULL,
    name_en TEXT,
    designation TEXT,
    designation_en TEXT,
    subject TEXT,
    phone TEXT,
    email TEXT,
    gender TEXT,
    address TEXT,
    photo_url TEXT,
    status TEXT DEFAULT 'active',
    joining_date TEXT,
    public_contact_role TEXT,
    public_contact_enabled BOOLEAN DEFAULT true,
    mpo_index_no TEXT,
    teacher_registration_no TEXT,
    nid_no TEXT,
    extended_profile JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Staff Table
CREATE TABLE IF NOT EXISTS public.staff (
    id TEXT PRIMARY KEY,
    employee_id TEXT UNIQUE,
    name_bn TEXT NOT NULL,
    name_en TEXT,
    designation TEXT,
    designation_en TEXT,
    phone TEXT,
    email TEXT,
    photo_url TEXT,
    status TEXT DEFAULT 'active',
    joining_date TEXT,
    public_contact_role TEXT,
    public_contact_enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Students Table
CREATE TABLE IF NOT EXISTS public.students (
    id TEXT PRIMARY KEY,
    student_id TEXT UNIQUE,
    roll_no INT,
    name_bn TEXT NOT NULL,
    name_en TEXT,
    class_name TEXT,
    section TEXT,
    gender TEXT,
    date_of_birth TEXT,
    blood_group TEXT,
    religion TEXT,
    father_name TEXT,
    mother_name TEXT,
    guardian_name TEXT,
    guardian_phone TEXT,
    current_village TEXT,
    current_upazila TEXT,
    current_district TEXT,
    permanent_village TEXT,
    permanent_upazila TEXT,
    permanent_district TEXT,
    photo_url TEXT,
    status TEXT DEFAULT 'active',
    admission_date TEXT,
    voter_no TEXT,
    voter_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Notices Table
CREATE TABLE IF NOT EXISTS public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_bn TEXT NOT NULL,
    title_en TEXT,
    body TEXT,
    notice_date TEXT,
    urgent BOOLEAN DEFAULT false,
    published BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Routines Table
CREATE TABLE IF NOT EXISTS public.routines (
    id TEXT PRIMARY KEY,
    class_name TEXT,
    section TEXT,
    day_of_week TEXT,
    start_time TEXT,
    end_time TEXT,
    subject_name TEXT,
    teacher_name TEXT,
    room TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create Exams Table
CREATE TABLE IF NOT EXISTS public.exams (
    id TEXT PRIMARY KEY,
    name_bn TEXT NOT NULL,
    exam_type TEXT,
    start_date TEXT,
    end_date TEXT,
    status TEXT DEFAULT 'draft',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Create Admissions Table
CREATE TABLE IF NOT EXISTS public.admissions (
    id TEXT PRIMARY KEY,
    application_no TEXT UNIQUE,
    academic_year INT,
    applied_class TEXT,
    applicant_name_bn TEXT,
    applicant_name_en TEXT,
    guardian_name TEXT,
    guardian_phone TEXT,
    application_date TEXT,
    status TEXT DEFAULT 'under_review',
    payment_amount NUMERIC DEFAULT 0,
    payment_status TEXT DEFAULT 'unpaid',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admissions ENABLE ROW LEVEL SECURITY;

-- Clean existing policies if re-running
DROP POLICY IF EXISTS "Allow public read teachers" ON public.teachers;
DROP POLICY IF EXISTS "Allow anon insert/update teachers" ON public.teachers;
DROP POLICY IF EXISTS "Allow public read staff" ON public.staff;
DROP POLICY IF EXISTS "Allow anon insert/update staff" ON public.staff;
DROP POLICY IF EXISTS "Allow public read students" ON public.students;
DROP POLICY IF EXISTS "Allow anon insert/update students" ON public.students;
DROP POLICY IF EXISTS "Allow public read notices" ON public.notices;
DROP POLICY IF EXISTS "Allow anon insert/update notices" ON public.notices;
DROP POLICY IF EXISTS "Allow public read routines" ON public.routines;
DROP POLICY IF EXISTS "Allow anon insert/update routines" ON public.routines;
DROP POLICY IF EXISTS "Allow public read exams" ON public.exams;
DROP POLICY IF EXISTS "Allow anon insert/update exams" ON public.exams;
DROP POLICY IF EXISTS "Allow public read admissions" ON public.admissions;
DROP POLICY IF EXISTS "Allow anon insert/update admissions" ON public.admissions;

-- Re-apply policies
CREATE POLICY "Allow public read teachers" ON public.teachers FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update teachers" ON public.teachers FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read staff" ON public.staff FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update staff" ON public.staff FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read students" ON public.students FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update students" ON public.students FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read notices" ON public.notices FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update notices" ON public.notices FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read routines" ON public.routines FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update routines" ON public.routines FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read exams" ON public.exams FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update exams" ON public.exams FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public read admissions" ON public.admissions FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update admissions" ON public.admissions FOR ALL USING (true) WITH CHECK (true);
