-- V87: hierarchical navigation registry (admin submenus + public submenu controls)
ALTER TABLE system_features ADD COLUMN IF NOT EXISTS parent_key VARCHAR(160);
CREATE INDEX IF NOT EXISTS idx_system_features_parent ON system_features(parent_key);

INSERT INTO system_features(feature_key,scope,feature_type,label_bn,label_en,group_name,icon,sort_order,parent_key,is_system) VALUES
('admin.students.list','admin','submenu','শিক্ষার্থী তালিকা','Student List','একাডেমিক','📋',21,'admin.students',true),
('admin.students.new','admin','submenu','নতুন শিক্ষার্থী','Add Student','একাডেমিক','➕',22,'admin.students',true),
('admin.students.search','admin','submenu','শিক্ষার্থী অনুসন্ধান','Student Search','একাডেমিক','🔎',23,'admin.students',true),
('admin.staff.teachers','admin','submenu','শিক্ষক ব্যবস্থাপনা','Teachers','একাডেমিক','👨‍🏫',31,'admin.staff',true),
('admin.staff.staff','admin','submenu','কর্মচারী ব্যবস্থাপনা','Staff','একাডেমিক','🧑‍💼',32,'admin.staff',true),
('admin.admission.applications','admin','submenu','ভর্তি আবেদন','Applications','একাডেমিক','📝',41,'admin.admission',true),
('admin.admission.test','admin','submenu','ভর্তি পরীক্ষা','Admission Test','একাডেমিক','✍️',42,'admin.admission',true),
('admin.admission.selection','admin','submenu','নির্বাচন ও ভর্তি','Selection & Enrollment','একাডেমিক','✅',43,'admin.admission',true),
('admin.attendance.daily','admin','submenu','দৈনিক উপস্থিতি','Daily Attendance','একাডেমিক','🕘',51,'admin.attendance',true),
('admin.attendance.reports','admin','submenu','উপস্থিতি রিপোর্ট','Attendance Reports','একাডেমিক','📊',52,'admin.attendance',true),
('admin.attendance.alerts','admin','submenu','অভিভাবক সতর্কতা','Guardian Alerts','একাডেমিক','🔔',53,'admin.attendance',true),
('admin.results.setup','admin','submenu','পরীক্ষা ও বিষয় সেটআপ','Exam & Subject Setup','একাডেমিক','⚙️',61,'admin.results',true),
('admin.results.marks','admin','submenu','মার্ক এন্ট্রি','Marks Entry','একাডেমিক','📝',62,'admin.results',true),
('admin.results.processing','admin','submenu','ফলাফল প্রসেসিং','Result Processing','একাডেমিক','🧮',63,'admin.results',true),
('admin.results.marksheet','admin','submenu','মার্কশিট ও প্রগ্রেস রিপোর্ট','Marksheet & Progress','একাডেমিক','📄',64,'admin.results',true),
('admin.results.tabulation','admin','submenu','ট্যাবুলেশন শিট','Tabulation Sheet','একাডেমিক','📑',65,'admin.results',true),
('admin.results.merit','admin','submenu','মেধা তালিকা','Merit List','একাডেমিক','🏆',66,'admin.results',true),
('admin.learning.content','admin','submenu','ডিজিটাল কনটেন্ট','Digital Content','শিক্ষা','📚',121,'admin.learning',true),
('admin.learning.syllabus','admin','submenu','সিলেবাস','Syllabus','শিক্ষা','📖',122,'admin.learning',true),
('admin.learning.progress','admin','submenu','শিক্ষার্থী অগ্রগতি','Learning Progress','শিক্ষা','📈',123,'admin.learning',true),
('admin.question.bank','admin','submenu','প্রশ্নব্যাংক','Question Bank','শিক্ষা','❓',131,'admin.question',true),
('admin.question.model','admin','submenu','মডেল প্রশ্ন','Model Questions','শিক্ষা','📝',132,'admin.question',true),
('admin.assignment.manage','admin','submenu','অ্যাসাইনমেন্ট','Assignments','শিক্ষা','📘',141,'admin.assignment',true),
('admin.assignment.review','admin','submenu','মূল্যায়ন','Evaluation','শিক্ষা','✅',142,'admin.assignment',true),
('admin.online_exam.setup','admin','submenu','অনলাইন পরীক্ষা সেটআপ','Exam Setup','শিক্ষা','⚙️',151,'admin.online_exam',true),
('admin.online_exam.results','admin','submenu','অনলাইন পরীক্ষার ফলাফল','Online Exam Results','শিক্ষা','📊',152,'admin.online_exam',true),
('admin.ai.tutor','admin','submenu','AI Tutor','AI Tutor','স্মার্ট ফিচার','✨',161,'admin.ai',true),
('admin.ai.analytics','admin','submenu','AI বিশ্লেষণ','AI Analytics','স্মার্ট ফিচার','🧠',162,'admin.ai',true),
('admin.documents.id','admin','submenu','ID Card','ID Card','রিপোর্ট','🪪',181,'admin.documents',true),
('admin.documents.marksheet','admin','submenu','Marksheet','Marksheet','রিপোর্ট','📄',182,'admin.documents',true),
('admin.documents.certificate','admin','submenu','Certificate','Certificate','রিপোর্ট','🏅',183,'admin.documents',true),
('admin.documents.admit','admin','submenu','Admit Card','Admit Card','রিপোর্ট','🎫',184,'admin.documents',true),
('admin.documents.tabulation','admin','submenu','Tabulation','Tabulation','রিপোর্ট','📑',185,'admin.documents',true),
('admin.documents.merit','admin','submenu','Merit List','Merit List','রিপোর্ট','🏆',186,'admin.documents',true),
('admin.users.accounts','admin','submenu','ব্যবহারকারী','User Accounts','নিরাপত্তা','👥',191,'admin.users',true),
('admin.users.roles','admin','submenu','রোল ও অনুমতি','Roles & Permissions','নিরাপত্তা','🔐',192,'admin.users',true),
('admin.users.sessions','admin','submenu','সেশন ও নিরাপত্তা','Sessions & Security','নিরাপত্তা','🛡️',193,'admin.users',true),
('admin.content.school','admin','submenu','বিদ্যালয় তথ্য','School Information','কনটেন্ট','🏫',201,'admin.content',true),
('admin.content.clubs','admin','submenu','ক্লাব ও সংগঠন','Clubs & Organizations','কনটেন্ট','🎯',202,'admin.content',true),
('admin.content.events','admin','submenu','ইভেন্ট ও অংশগ্রহণকারী','Events & Participants','কনটেন্ট','🎉',203,'admin.content',true),
('admin.content.achievements','admin','submenu','অর্জন ও পুরস্কার','Achievements','কনটেন্ট','🏆',204,'admin.content',true),
('admin.feature_control.system','admin','submenu','সিস্টেম Feature ON/OFF','System Feature Control','নিরাপত্তা','🧩',241,'admin.feature_control',true),
('admin.feature_control.public','admin','submenu','View Site Menu ON/OFF','Public Menu Control','নিরাপত্তা','🌐',242,'admin.feature_control',true),
('admin.feature_control.custom','admin','submenu','নতুন Feature যোগ','Custom Features','নিরাপত্তা','➕',243,'admin.feature_control',true),

('public.nav.institution.about','public','submenu','বিদ্যালয় পরিচিতি','School Information','প্রাতিষ্ঠানিক তথ্য','🏫',21,'public.nav.institution',true),
('public.nav.institution.message','public','submenu','সভাপতি ও প্রধান শিক্ষকের বাণী','Leadership Messages','প্রাতিষ্ঠানিক তথ্য','💬',22,'public.nav.institution',true),
('public.nav.institution.committee','public','submenu','পরিচালনা কমিটি','Committee','প্রাতিষ্ঠানিক তথ্য','👥',23,'public.nav.institution',true),
('public.nav.institution.rules','public','submenu','নিয়ম-কানুন','Rules','প্রাতিষ্ঠানিক তথ্য','📜',24,'public.nav.institution',true),
('public.nav.institution.library','public','submenu','লাইব্রেরি','Library','প্রাতিষ্ঠানিক তথ্য','📚',25,'public.nav.institution',true),
('public.nav.institution.curriculum','public','submenu','পাঠ্যক্রম ও পাঠ্যপুস্তক','Curriculum & Textbooks','প্রাতিষ্ঠানিক তথ্য','📖',26,'public.nav.institution',true),
('public.nav.sport.sports','public','submenu','বার্ষিক ক্রীড়া','Annual Sports','ক্রীড়া ও সংস্কৃতি','⚽',31,'public.nav.sport',true),
('public.nav.sport.clubs','public','submenu','ক্লাব ও সংগঠন','Clubs','ক্রীড়া ও সংস্কৃতি','🎯',32,'public.nav.sport',true),
('public.nav.sport.culture','public','submenu','সাংস্কৃতিক অনুষ্ঠান','Cultural Programs','ক্রীড়া ও সংস্কৃতি','🎭',33,'public.nav.sport',true),
('public.nav.sport.achievements','public','submenu','অর্জন ও পুরস্কার','Achievements','ক্রীড়া ও সংস্কৃতি','🏆',34,'public.nav.sport',true),
('public.nav.staff.active','public','submenu','সক্রিয় শিক্ষকবৃন্দ','Active Teachers','শিক্ষক ও কর্মচারী','👨‍🏫',41,'public.nav.staff',true),
('public.nav.staff.former','public','submenu','সাবেক শিক্ষকবৃন্দ','Former Teachers','শিক্ষক ও কর্মচারী','📚',42,'public.nav.staff',true),
('public.nav.staff.employees','public','submenu','কর্মচারীবৃন্দ','Employees','শিক্ষক ও কর্মচারী','🧑‍💼',43,'public.nav.staff',true),
('public.nav.students.all','public','submenu','সকল শিক্ষার্থী','All Students','শিক্ষার্থীর তথ্য','🎓',51,'public.nav.students',true),
('public.nav.students.scholarship','public','submenu','বৃত্তিপ্রাপ্ত শিক্ষার্থী','Scholarship Students','শিক্ষার্থীর তথ্য','🏅',52,'public.nav.students',true),
('public.nav.students.distinguished','public','submenu','কৃতি শিক্ষার্থী','Distinguished Students','শিক্ষার্থীর তথ্য','🌟',53,'public.nav.students',true),
('public.nav.results.admission','public','submenu','ভর্তি পরীক্ষা','Admission Test','পরীক্ষার ফলাফল','📝',61,'public.nav.results',true),
('public.nav.results.internal','public','submenu','অভ্যন্তরীণ পরীক্ষা','Internal Exams','পরীক্ষার ফলাফল','📊',62,'public.nav.results',true),
('public.nav.results.ssc','public','submenu','SSC ফলাফল','SSC Results','পরীক্ষার ফলাফল','🎓',63,'public.nav.results',true),
('public.nav.results.analysis','public','submenu','ফলাফল বিশ্লেষণ','Result Analysis','পরীক্ষার ফলাফল','📈',64,'public.nav.results',true),
('public.nav.guide.syllabus','public','submenu','সিলেবাস','Syllabus','শিক্ষার্থীর গাইড','📖',71,'public.nav.guide',true),
('public.nav.guide.learning','public','submenu','ডিজিটাল লার্নিং','Digital Learning','শিক্ষার্থীর গাইড','💻',72,'public.nav.guide',true),
('public.nav.guide.question','public','submenu','প্রশ্নব্যাংক ও মডেল প্রশ্ন','Question Bank','শিক্ষার্থীর গাইড','❓',73,'public.nav.guide',true),
('public.nav.guide.assignment','public','submenu','অ্যাসাইনমেন্ট ও মক টেস্ট','Assignments & Mock Tests','শিক্ষার্থীর গাইড','📝',74,'public.nav.guide',true),
('public.nav.guide.online','public','submenu','অনলাইন পরীক্ষা','Online Exam','শিক্ষার্থীর গাইড','🧪',75,'public.nav.guide',true),
('public.nav.guide.ai','public','submenu','AI শিক্ষা সহকারী','AI Assistant','শিক্ষার্থীর গাইড','✨',76,'public.nav.guide',true)
ON CONFLICT(feature_key) DO NOTHING;
