-- V90: full teacher/staff/student form fields based on supplied school forms.
ALTER TABLE students
  ADD COLUMN IF NOT EXISTS primary_school_name VARCHAR(250),
  ADD COLUMN IF NOT EXISTS primary_registration_no VARCHAR(100),
  ADD COLUMN IF NOT EXISTS primary_completion_year INT,
  ADD COLUMN IF NOT EXISTS religion VARCHAR(50),
  ADD COLUMN IF NOT EXISTS student_nid_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS father_name_en VARCHAR(180),
  ADD COLUMN IF NOT EXISTS father_nid_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS father_profession VARCHAR(120),
  ADD COLUMN IF NOT EXISTS father_mobile VARCHAR(40),
  ADD COLUMN IF NOT EXISTS father_abroad_country VARCHAR(120),
  ADD COLUMN IF NOT EXISTS mother_name_en VARCHAR(180),
  ADD COLUMN IF NOT EXISTS mother_nid_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS mother_profession VARCHAR(120),
  ADD COLUMN IF NOT EXISTS mother_mobile VARCHAR(40),
  ADD COLUMN IF NOT EXISTS mother_death_year INT,
  ADD COLUMN IF NOT EXISTS guardian_name_en VARCHAR(180),
  ADD COLUMN IF NOT EXISTS guardian_nid_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS current_village VARCHAR(150),
  ADD COLUMN IF NOT EXISTS current_post_office VARCHAR(150),
  ADD COLUMN IF NOT EXISTS current_upazila VARCHAR(150),
  ADD COLUMN IF NOT EXISTS current_district VARCHAR(150),
  ADD COLUMN IF NOT EXISTS permanent_village VARCHAR(150),
  ADD COLUMN IF NOT EXISTS permanent_post_office VARCHAR(150),
  ADD COLUMN IF NOT EXISTS permanent_upazila VARCHAR(150),
  ADD COLUMN IF NOT EXISTS permanent_district VARCHAR(150),
  ADD COLUMN IF NOT EXISTS special_needs VARCHAR(250),
  ADD COLUMN IF NOT EXISTS additional_notes TEXT,
  ADD COLUMN IF NOT EXISTS extended_profile JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE teachers
  ADD COLUMN IF NOT EXISTS nid_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS tin_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS birth_registration_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS whatsapp_no VARCHAR(40),
  ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10),
  ADD COLUMN IF NOT EXISTS religion VARCHAR(50),
  ADD COLUMN IF NOT EXISTS marital_status VARCHAR(50),
  ADD COLUMN IF NOT EXISTS nationality VARCHAR(60),
  ADD COLUMN IF NOT EXISTS father_name_bn VARCHAR(180),
  ADD COLUMN IF NOT EXISTS father_name_en VARCHAR(180),
  ADD COLUMN IF NOT EXISTS mother_name_bn VARCHAR(180),
  ADD COLUMN IF NOT EXISTS mother_name_en VARCHAR(180),
  ADD COLUMN IF NOT EXISTS first_joining_date DATE,
  ADD COLUMN IF NOT EXISTS first_mpo_date DATE,
  ADD COLUMN IF NOT EXISTS current_post_joining_date DATE,
  ADD COLUMN IF NOT EXISTS current_mpo_date DATE,
  ADD COLUMN IF NOT EXISTS previous_institution_joining_date DATE,
  ADD COLUMN IF NOT EXISTS previous_institution_mpo_date DATE,
  ADD COLUMN IF NOT EXISTS appointment_date DATE,
  ADD COLUMN IF NOT EXISTS appointment_authority VARCHAR(180),
  ADD COLUMN IF NOT EXISTS mpo_index_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS teacher_registration_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS registration_date DATE,
  ADD COLUMN IF NOT EXISTS teacher_portal_id VARCHAR(120),
  ADD COLUMN IF NOT EXISTS permanent_address TEXT,
  ADD COLUMN IF NOT EXISTS extended_profile JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE staff
  ADD COLUMN IF NOT EXISTS nid_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS tin_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS birth_registration_no VARCHAR(80),
  ADD COLUMN IF NOT EXISTS whatsapp_no VARCHAR(40),
  ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10),
  ADD COLUMN IF NOT EXISTS religion VARCHAR(50),
  ADD COLUMN IF NOT EXISTS marital_status VARCHAR(50),
  ADD COLUMN IF NOT EXISTS nationality VARCHAR(60),
  ADD COLUMN IF NOT EXISTS father_name_bn VARCHAR(180),
  ADD COLUMN IF NOT EXISTS father_name_en VARCHAR(180),
  ADD COLUMN IF NOT EXISTS mother_name_bn VARCHAR(180),
  ADD COLUMN IF NOT EXISTS mother_name_en VARCHAR(180),
  ADD COLUMN IF NOT EXISTS first_joining_date DATE,
  ADD COLUMN IF NOT EXISTS current_post_joining_date DATE,
  ADD COLUMN IF NOT EXISTS appointment_date DATE,
  ADD COLUMN IF NOT EXISTS appointment_authority VARCHAR(180),
  ADD COLUMN IF NOT EXISTS permanent_address TEXT,
  ADD COLUMN IF NOT EXISTS extended_profile JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_students_primary_reg ON students(primary_registration_no);
CREATE INDEX IF NOT EXISTS idx_students_father_nid ON students(father_nid_no);
CREATE INDEX IF NOT EXISTS idx_students_mother_nid ON students(mother_nid_no);
CREATE INDEX IF NOT EXISTS idx_teachers_nid ON teachers(nid_no);
CREATE INDEX IF NOT EXISTS idx_teachers_registration ON teachers(teacher_registration_no);
