import React, { useState, useEffect } from 'react';
import {
  getSupabaseConfig,
  saveSupabaseConfig,
  testSupabaseConnection,
  uploadLocalToSupabase,
  downloadSupabaseToLocal
} from './supabaseClient';

export default function SupabaseSyncModal({ isOpen, onClose }) {
  const [url, setUrl] = useState('');
  const [anonKey, setAnonKey] = useState('');
  const [autoSync, setAutoSync] = useState(true);
  const [status, setStatus] = useState({ type: '', message: '' });
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('setup'); // 'setup' | 'sync' | 'sql'

  useEffect(() => {
    if (isOpen) {
      const cfg = getSupabaseConfig();
      setUrl(cfg.url);
      setAnonKey(cfg.anonKey);
      setAutoSync(cfg.autoSync);
      setStatus({
        type: cfg.isConfigured ? 'success' : 'info',
        message: cfg.isConfigured ? '🟢 ক্লাউড ডেটাবেস কনফিগার করা আছে' : 'ℹ️ Supabase প্রজেক্টের URL ও Key দিন'
      });
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleSave = async (e) => {
    if (e) e.preventDefault();
    setLoading(true);
    setStatus({ type: 'info', message: 'সংযোগে পরীক্ষা করা হচ্ছে...' });
    try {
      await testSupabaseConnection(url, anonKey);
      saveSupabaseConfig(url, anonKey, autoSync);
      setStatus({ type: 'success', message: '✅ সফলভাবে Supabase ক্লাউডে সংযুক্ত হয়েছে!' });
    } catch (err) {
      setStatus({ type: 'error', message: '❌ ' + (err.message || 'সংযোগে ব্যর্থ হয়েছে') });
    } finally {
      setLoading(false);
    }
  };

  const handleUpload = async () => {
    setLoading(true);
    setStatus({ type: 'info', message: '⬆️ ল্যাপটপের ডেটা ক্লাউডে আপলোড হচ্ছে...' });
    try {
      const res = await uploadLocalToSupabase();
      setStatus({
        type: 'success',
        message: `✅ সফলভাবে ক্লাউডে আপলোড হয়েছে! (শিক্ষক: ${res.teachers} জন, শিক্ষার্থী: ${res.students} জন, কর্মচারী: ${res.staff} জন)`
      });
    } catch (err) {
      setStatus({ type: 'error', message: '❌ ' + (err.message || 'আপলোড ব্যর্থ হয়েছে') });
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    setLoading(true);
    setStatus({ type: 'info', message: '⬇️ ক্লাউড থেকে ডেটা নামানো হচ্ছে...' });
    try {
      const res = await downloadSupabaseToLocal();
      setStatus({
        type: 'success',
        message: `✅ সফলভাবে সিঙ্ক সম্পন্ন! (শিক্ষক: ${res.teachers} জন, শিক্ষার্থী: ${res.students} জন)`
      });
      setTimeout(() => {
        window.location.reload();
      }, 1200);
    } catch (err) {
      setStatus({ type: 'error', message: '❌ ' + (err.message || 'ডাউনলোড ব্যর্থ হয়েছে') });
    } finally {
      setLoading(false);
    }
  };

  const copySqlCode = () => {
    const sql = `-- Magra School Supabase Schema
CREATE TABLE IF NOT EXISTS public.teachers (
    id TEXT PRIMARY KEY, employee_id TEXT UNIQUE, name_bn TEXT NOT NULL, name_en TEXT, designation TEXT, designation_en TEXT, subject TEXT, phone TEXT, email TEXT, gender TEXT, address TEXT, photo_url TEXT, status TEXT DEFAULT 'active', joining_date TEXT, public_contact_role TEXT, public_contact_enabled BOOLEAN DEFAULT true, mpo_index_no TEXT, teacher_registration_no TEXT, nid_no TEXT, extended_profile JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.staff (
    id TEXT PRIMARY KEY, employee_id TEXT UNIQUE, name_bn TEXT NOT NULL, name_en TEXT, designation TEXT, designation_en TEXT, phone TEXT, email TEXT, photo_url TEXT, status TEXT DEFAULT 'active', joining_date TEXT, public_contact_role TEXT, public_contact_enabled BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.students (
    id TEXT PRIMARY KEY, student_id TEXT UNIQUE, roll_no INT, name_bn TEXT NOT NULL, name_en TEXT, class_name TEXT, section TEXT, gender TEXT, date_of_birth TEXT, blood_group TEXT, religion TEXT, father_name TEXT, mother_name TEXT, guardian_name TEXT, guardian_phone TEXT, current_village TEXT, current_upazila TEXT, current_district TEXT, permanent_village TEXT, permanent_upazila TEXT, permanent_district TEXT, photo_url TEXT, status TEXT DEFAULT 'active', admission_date TEXT, voter_no TEXT, voter_name TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title_bn TEXT NOT NULL, title_en TEXT, body TEXT, notice_date TEXT, urgent BOOLEAN DEFAULT false, published BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read teachers" ON public.teachers FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update teachers" ON public.teachers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read staff" ON public.staff FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update staff" ON public.staff FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read students" ON public.students FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update students" ON public.students FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read notices" ON public.notices FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update notices" ON public.notices FOR ALL USING (true) WITH CHECK (true);`;
    navigator.clipboard.writeText(sql);
    alert('SQL কোড কপি হয়েছে! Supabase SQL Editor এ পেস্ট করে RUN চাপুন।');
  };

  return (
    <div className="modal-overlay" style={{ zIndex: 10000, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(4px)' }}>
      <div className="modal-card" style={{ maxWidth: '640px', width: '92%', background: '#fff', borderRadius: '14px', overflow: 'hidden', boxShadow: '0 20px 40px rgba(0,0,0,0.25)', border: '1px solid #cbd5e1' }}>
        
        {/* Header */}
        <div style={{ background: 'linear-gradient(135deg, #0b8050, #064e3b)', color: '#fff', padding: '16px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span style={{ fontSize: '24px' }}>☁️</span>
            <div>
              <h3 style={{ margin: 0, fontSize: '17px', fontWeight: 800 }}>Supabase ক্লাউড ডেটাবেস সংযোগ ও সিঙ্ক</h3>
              <p style={{ margin: 0, fontSize: '11px', opacity: 0.9 }}>মোবাইল ও ল্যাপটপের সমস্ত ডেটা এক জায়গায় লাইভ সিঙ্ক রাখুন</p>
            </div>
          </div>
          <button type="button" onClick={onClose} style={{ background: 'rgba(255,255,255,0.2)', border: 'none', color: '#fff', fontSize: '18px', width: '32px', height: '32px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>✕</button>
        </div>

        {/* Tabs */}
        <div style={{ display: 'flex', borderBottom: '1px solid #e2e8f0', background: '#f8fafc' }}>
          <button
            type="button"
            onClick={() => setActiveTab('setup')}
            style={{ flex: 1, padding: '12px', border: 'none', background: activeTab === 'setup' ? '#fff' : 'transparent', fontWeight: activeTab === 'setup' ? 700 : 500, color: activeTab === 'setup' ? '#0b8050' : '#64748b', borderBottom: activeTab === 'setup' ? '3px solid #0b8050' : 'none', cursor: 'pointer', fontSize: '13px' }}
          >
            ⚙️ ক্লাউড সংযোগ (Setup)
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('sync')}
            style={{ flex: 1, padding: '12px', border: 'none', background: activeTab === 'sync' ? '#fff' : 'transparent', fontWeight: activeTab === 'sync' ? 700 : 500, color: activeTab === 'sync' ? '#0b8050' : '#64748b', borderBottom: activeTab === 'sync' ? '3px solid #0b8050' : 'none', cursor: 'pointer', fontSize: '13px' }}
          >
            🔄 ডেটা সিঙ্ক (Sync Data)
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('sql')}
            style={{ flex: 1, padding: '12px', border: 'none', background: activeTab === 'sql' ? '#fff' : 'transparent', fontWeight: activeTab === 'sql' ? 700 : 500, color: activeTab === 'sql' ? '#0b8050' : '#64748b', borderBottom: activeTab === 'sql' ? '3px solid #0b8050' : 'none', cursor: 'pointer', fontSize: '13px' }}
          >
            📋 SQL টেবিল স্ক্রিপ্ট
          </button>
        </div>

        {/* Content Body */}
        <div style={{ padding: '20px', maxHeight: '68vh', overflowY: 'auto' }}>
          {status.message && (
            <div style={{
              padding: '10px 14px',
              borderRadius: '8px',
              fontSize: '12px',
              fontWeight: 600,
              marginBottom: '16px',
              background: status.type === 'error' ? '#fef2f2' : status.type === 'success' ? '#f0fdf4' : '#eff6ff',
              color: status.type === 'error' ? '#b91c1c' : status.type === 'success' ? '#15803d' : '#1d4ed8',
              border: `1px solid ${status.type === 'error' ? '#fecaca' : status.type === 'success' ? '#bbf7d0' : '#bfdbfe'}`
            }}>
              {status.message}
            </div>
          )}

          {activeTab === 'setup' && (
            <form onSubmit={handleSave}>
              <div style={{ marginBottom: '14px' }}>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: 700, color: '#334155', marginBottom: '4px' }}>
                  Supabase Project URL:
                </label>
                <input
                  type="text"
                  placeholder="https://xyzcompany.supabase.co"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '13px', boxSizing: 'border-box' }}
                />
                <span style={{ fontSize: '11px', color: '#64748b' }}>Supabase ড্যাশবোর্ডের Settings ➔ API ➔ Project URL</span>
              </div>

              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: 700, color: '#334155', marginBottom: '4px' }}>
                  Supabase Anon Key (Public API Key):
                </label>
                <textarea
                  rows="3"
                  placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  value={anonKey}
                  onChange={(e) => setAnonKey(e.target.value)}
                  style={{ width: '100%', padding: '10px 12px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '12px', boxSizing: 'border-box', fontFamily: 'monospace' }}
                />
                <span style={{ fontSize: '11px', color: '#64748b' }}>Supabase ড্যাশবোর্ডের Settings ➔ API ➔ anon public key</span>
              </div>

              <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end', marginTop: '16px' }}>
                <button
                  type="submit"
                  disabled={loading}
                  style={{ background: '#0b8050', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '8px', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}
                >
                  {loading ? 'পরীক্ষা করা হচ্ছে...' : '💾 সেভ ও কানেক্ট করুন'}
                </button>
              </div>

              <div style={{ marginTop: '20px', padding: '14px', background: '#f8fafc', borderRadius: '10px', border: '1px solid #e2e8f0', fontSize: '12px', color: '#475569' }}>
                <strong style={{ color: '#0f172a', display: 'block', marginBottom: '6px' }}>💡 কীভাবে ফ্রি Supabase অ্যাকাউন্ট পাবেন? (মাত্র ২ মিনিট):</strong>
                <ol style={{ margin: '0 0 0 16px', padding: 0, lineHeight: 1.6 }}>
                  <li><a href="https://supabase.com" target="_blank" rel="noreferrer" style={{ color: '#2563eb', fontWeight: 600 }}>supabase.com</a> এ গিয়ে <strong>Start your project</strong> চাপুন।</li>
                  <li>একটি নতুন প্রজেক্ট তৈরি করে <strong>SQL Editor</strong> এ যান এবং আমাদের দেওয়া <strong>SQL টেবিল স্ক্রিপ্ট</strong> রান করুন।</li>
                  <li><strong>Project Settings ➔ API</strong> থেকে URL এবং anon key কপি করে উপরে পেস্ট করুন!</li>
                </ol>
              </div>
            </form>
          )}

          {activeTab === 'sync' && (
            <div>
              <p style={{ fontSize: '13px', color: '#334155', lineHeight: 1.5, margin: '0 0 16px' }}>
                ল্যাপটপ থেকে আপনার এন্ট্রিকৃত শিক্ষক ও শিক্ষার্থীদের তথ্য ক্লাউডে পাঠাতে অথবা ক্লাউড থেকে সব ডেটা মোবাইল/ল্যাপটপে লোড করতে নিচের বাটনগুলো ব্যবহার করুন:
              </p>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '20px' }}>
                <div style={{ padding: '16px', border: '1.5px solid #86efac', background: '#f0fdf4', borderRadius: '10px', textAlign: 'center' }}>
                  <span style={{ fontSize: '28px', display: 'block', marginBottom: '6px' }}>⬆️</span>
                  <h4 style={{ margin: '0 0 4px', color: '#166534', fontSize: '14px' }}>ল্যাপটপের ডেটা ক্লাউডে পাঠান</h4>
                  <p style={{ fontSize: '11px', color: '#15803d', margin: '0 0 12px' }}>ল্যাপটপের ১৫ জন শিক্ষক ও ছাত্রদের তথ্য Supabase ক্লাউডে আপলোড হবে</p>
                  <button
                    type="button"
                    onClick={handleUpload}
                    disabled={loading}
                    style={{ width: '100%', background: '#0b8050', color: '#fff', border: 'none', padding: '9px 14px', borderRadius: '6px', fontWeight: 700, cursor: 'pointer' }}
                  >
                    {loading ? 'আপলোড হচ্ছে...' : '⬆️ ক্লাউডে আপলোড করুন'}
                  </button>
                </div>

                <div style={{ padding: '16px', border: '1.5px solid #93c5fd', background: '#eff6ff', borderRadius: '10px', textAlign: 'center' }}>
                  <span style={{ fontSize: '28px', display: 'block', marginBottom: '6px' }}>⬇️</span>
                  <h4 style={{ margin: '0 0 4px', color: '#1e40af', fontSize: '14px' }}>ক্লাউড থেকে ডেটা নামিয়ে নিন</h4>
                  <p style={{ fontSize: '11px', color: '#1d4ed8', margin: '0 0 12px' }}>মোবাইল বা যে কোনো ডিভাইসে ক্লাউডের সর্বশেষ তথ্য সিঙ্ক হবে</p>
                  <button
                    type="button"
                    onClick={handleDownload}
                    disabled={loading}
                    style={{ width: '100%', background: '#2563eb', color: '#fff', border: 'none', padding: '9px 14px', borderRadius: '6px', fontWeight: 700, cursor: 'pointer' }}
                  >
                    {loading ? 'ডাউনলোড হচ্ছে...' : '⬇️ ডেটা সিঙ্ক করুন'}
                  </button>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'sql' && (
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                <span style={{ fontSize: '12px', fontWeight: 700, color: '#334155' }}>Supabase SQL Editor স্ক্রিপ্ট:</span>
                <button
                  type="button"
                  onClick={copySqlCode}
                  style={{ background: '#0b8050', color: '#fff', border: 'none', padding: '6px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: 700, cursor: 'pointer' }}
                >
                  📋 কোড কপি করুন (Copy SQL)
                </button>
              </div>
              <pre style={{ background: '#1e293b', color: '#f8fafc', padding: '14px', borderRadius: '8px', fontSize: '11px', overflowX: 'auto', maxHeight: '240px', lineHeight: 1.4 }}>
{`-- 1. Create Teachers Table
CREATE TABLE IF NOT EXISTS public.teachers (
    id TEXT PRIMARY KEY,
    employee_id TEXT UNIQUE,
    name_bn TEXT NOT NULL,
    name_en TEXT,
    designation TEXT,
    designation_en TEXT,
    subject TEXT,
    phone TEXT,
    email TEXT,
    gender TEXT,
    address TEXT,
    photo_url TEXT,
    status TEXT DEFAULT 'active',
    joining_date TEXT,
    public_contact_role TEXT,
    public_contact_enabled BOOLEAN DEFAULT true,
    mpo_index_no TEXT,
    teacher_registration_no TEXT,
    nid_no TEXT,
    extended_profile JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Students Table
CREATE TABLE IF NOT EXISTS public.students (
    id TEXT PRIMARY KEY,
    student_id TEXT UNIQUE,
    roll_no INT,
    name_bn TEXT NOT NULL,
    name_en TEXT,
    class_name TEXT,
    section TEXT,
    gender TEXT,
    date_of_birth TEXT,
    blood_group TEXT,
    religion TEXT,
    father_name TEXT,
    mother_name TEXT,
    guardian_name TEXT,
    guardian_phone TEXT,
    current_village TEXT,
    current_upazila TEXT,
    current_district TEXT,
    permanent_village TEXT,
    permanent_upazila TEXT,
    permanent_district TEXT,
    photo_url TEXT,
    status TEXT DEFAULT 'active',
    admission_date TEXT,
    voter_no TEXT,
    voter_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS and public policies
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read teachers" ON public.teachers FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update teachers" ON public.teachers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read students" ON public.students FOR SELECT USING (true);
CREATE POLICY "Allow anon insert/update students" ON public.students FOR ALL USING (true) WITH CHECK (true);`}
              </pre>
            </div>
          )}

        </div>

        {/* Footer */}
        <div style={{ padding: '12px 20px', background: '#f8fafc', borderTop: '1px solid #e2e8f0', display: 'flex', justifyContent: 'flex-end' }}>
          <button
            type="button"
            onClick={onClose}
            style={{ background: '#64748b', color: '#fff', border: 'none', padding: '8px 18px', borderRadius: '6px', fontWeight: 600, cursor: 'pointer', fontSize: '12px' }}
          >
            বন্ধ করুন (Close)
          </button>
        </div>

      </div>
    </div>
  );
}
