import fs from 'fs';
import path from 'path';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const checks=[];
const ok=(name,cond,detail='')=>checks.push({name,pass:Boolean(cond),detail});
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const server=read('backend/src/server.js');
const main=read('frontend/src/main.jsx');
const nav=read('frontend/src/publicNavConfig.js');
const pkg=JSON.parse(read('frontend/package.json'));
const migrations=fs.readdirSync(path.join(root,'database/migrations')).filter(x=>x.endsWith('.sql')).sort();

ok('Backend version is V77', server.includes("version:'V77'"));
ok('Startup banner is V77', server.includes('Magra School API V77 running'));
ok('Health endpoint exists', server.includes("app.get('/api/health'"));
ok('Readiness performs PostgreSQL SELECT 1', /pool\.query\(['"]SELECT 1['"]\)/.test(server));
ok('Production environment validation retained', server.includes('validateProductionEnv'));
ok('JWT authentication retained', server.includes('jsonwebtoken') || server.includes('jwt.verify'));
ok('Rate limiting retained', server.includes('rateLimit'));
ok('Helmet retained', server.includes('helmet'));
ok('CORS allowlist retained', server.includes('corsOptions') || server.includes('CORS_ORIGIN'));
ok('Frontend production build command exists', pkg.scripts?.build==='vite build');
ok('React/Vite dependencies exist', Boolean(pkg.dependencies?.react && pkg.dependencies?.vite && pkg.dependencies?.['react-dom']));
ok('PWA support retained', Boolean(pkg.dependencies?.['vite-plugin-pwa']) && /vite-plugin-pwa/.test(main) || /vite-plugin-pwa/.test(read('frontend/vite.config.js')));
ok('Locked public reference 1→2→3→4 retained', /1.?→.?2.?→.?3.?→.?4|1.?->.?2.?->.?3.?->.?4/.test(nav));
ok('EIIN 114290 retained', server.includes('114290') || main.includes('114290'));
ok('Official document workflow retained', /issued|document/i.test(main) && fs.existsSync(path.join(root,'database/migrations/025_document_integrity.sql')));
ok('Role management retained', /role/i.test(main) && /admin/i.test(server));
ok('At least 25 migrations present', migrations.length>=20, `${migrations.length} migrations`);
ok('Backup script retained', fs.existsSync(path.join(root,'scripts/backup.sh')));
ok('Restore script retained', fs.existsSync(path.join(root,'scripts/restore.sh')));
ok('V76 regression suite retained', fs.existsSync(path.join(root,'scripts/qa_v76.mjs')));
ok('V75 preflight retained', fs.existsSync(path.join(root,'scripts/preflight_v75.mjs')));
const pass=checks.filter(x=>x.pass).length;
console.log(`V77 FINAL-CANDIDATE AUDIT: ${pass}/${checks.length} PASS`);
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} - ${c.name}${c.detail?' :: '+c.detail:''}`);
if(pass!==checks.length) process.exit(1);
