import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(); const checks=[];
const ok=(name,pass)=>checks.push([name,!!pass]);
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const server=read('backend/src/server.js');
const main=read('frontend/src/main.jsx');
const css=read('frontend/src/styles.css');
const nav=read('frontend/src/publicNavConfig.js');
const pkg=JSON.parse(read('frontend/package.json'));
ok('Backend version is V78 source baseline', server.includes("version:'V78'"));
ok('Health endpoint performs DB readiness query', /api\/health[\s\S]*?res\.json/.test(server));
ok('Ready endpoint performs SELECT 1', /\/ready[\s\S]*?SELECT 1/.test(server));
ok('Production build script exists', pkg.scripts?.build === 'vite build');
ok('React/Vite entry exists', fs.existsSync(path.join(root,'frontend/src/main.jsx')));
ok('School logo asset exists', fs.existsSync(path.join(root,'frontend/public/school-logo.png')));
ok('School building asset exists', fs.existsSync(path.join(root,'frontend/public/school-building.jpg')));
ok('Locked final public nav marker exists', nav.includes('Final reference-driven public navigation'));
ok('EIIN 114290 retained', /114290/.test(main));
ok('School name retained', main.includes('মগড়া পালস্‌ ইউনিয়ন উচ্চ বিদ্যালয়'));
ok('Leadership names retained', ['নেয়ামুল হক খান','মুহাম্মদ শফিকুল ইসলাম','তাপসী সরকার','মুহাম্মদ আবুবকর সিদ্দিক'].every(n=>main.includes(n)));
ok('Public reference gallery lightbox retained', main.includes('ref-lightbox'));
ok('Login UI retained', /Login|লগইন/.test(main));
ok('Responsive styles retained', css.includes('@media'));
ok('Security module exists', fs.existsSync(path.join(root,'backend/src/security.js')));
ok('Migration set exists', fs.readdirSync(path.join(root,'database/migrations')).filter(x=>x.endsWith('.sql')).length >= 20);
ok('Official document migration exists', fs.existsSync(path.join(root,'database/migrations/025_document_integrity.sql')));
ok('Backup script exists', fs.existsSync(path.join(root,'scripts/backup.sh')));
ok('Restore script exists', fs.existsSync(path.join(root,'scripts/restore.sh')));
ok('No javascript: URLs in frontend source', !/javascript\s*:/i.test(main+nav));
ok('No TODO/FIXME markers in application source', !/TODO|FIXME/.test(server+main+css+nav));
const pass=checks.filter(x=>x[1]).length;
for (const [name,p] of checks) console.log(`${p?'PASS':'FAIL'} ${name}`);
console.log(`V79 FINAL READINESS AUDIT: ${pass}/${checks.length} PASS`);
if(pass!==checks.length) process.exit(1);
