import fs from 'fs';
import path from 'path';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const checks=[];
const ok=(name,cond,detail='')=>checks.push({name,pass:Boolean(cond),detail});
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const server=read('backend/src/server.js');
const main=read('frontend/src/main.jsx');
const css=read('frontend/src/styles.css');
const nav=read('frontend/src/publicNavConfig.js');
const fpkg=JSON.parse(read('frontend/package.json'));
const bpkg=JSON.parse(read('backend/package.json'));

ok('Backend version is V78', server.includes("version:'V78'"));
ok('Startup banner is V78', server.includes('Magra School API V78 running'));
ok('Readiness uses PostgreSQL SELECT 1', /pool\.query\(['"]SELECT 1['"]\)/.test(server));
ok('Production environment validation retained', server.includes('validateProductionEnv'));
ok('JWT authentication retained', server.includes('jwt.verify') || server.includes('jsonwebtoken'));
ok('Rate limiting retained', server.includes('rateLimit'));
ok('Helmet retained', server.includes('helmet'));
ok('Explicit CORS configuration retained', server.includes('CORS_ORIGIN'));
ok('Frontend production build script exists', fpkg.scripts?.build==='vite build');
ok('React/Vite/PWA packages retained', Boolean(fpkg.dependencies?.react && fpkg.dependencies?.vite && fpkg.dependencies?.['vite-plugin-pwa']));
ok('Backend PostgreSQL driver retained', Boolean(bpkg.dependencies?.pg));
ok('Locked public reference 1→2→3→4 retained', nav.includes('1→2→3→4') || nav.includes('1->2->3->4'));
ok('School EIIN 114290 retained', main.includes('114290') || server.includes('114290'));
ok('School logo asset exists', fs.existsSync(path.join(root,'frontend/public/school-logo.png')));
ok('School building asset exists', fs.existsSync(path.join(root,'frontend/public/school-building.jpg')));
ok('Login form exists', main.includes('id="login"') && main.includes('/auth/login'));
ok('Role-aware portal routing retained', main.includes('/portal') && main.includes('/admin'));
ok('Admin user role management retained', main.includes('/users/') && main.includes('reset-password'));
ok('Official document issue module retained', main.includes('DocumentPanel') && server.includes('/api/documents'));
ok('Backup script exists', fs.existsSync(path.join(root,'scripts/backup.sh')));
ok('Restore script exists', fs.existsSync(path.join(root,'scripts/restore.sh')));
ok('At least 20 SQL migrations exist', fs.readdirSync(path.join(root,'database/migrations')).filter(x=>x.endsWith('.sql')).length>=20);
ok('No TODO/FIXME markers in application source', !/(TODO|FIXME)/.test(server+main+css));
ok('No javascript: URLs in frontend source', !/javascript:/i.test(main+nav));
ok('External link safety retained', main.includes('noopener') || main.includes('rel="noopener noreferrer"'));

const pass=checks.filter(x=>x.pass).length;
console.log(`V78 FINAL ACCEPTANCE AUDIT: ${pass}/${checks.length} PASS`);
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} - ${c.name}${c.detail?' :: '+c.detail:''}`);
if(pass!==checks.length) process.exit(1);
