import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const ok=(name,cond)=>{if(!cond)throw new Error('FAIL: '+name);console.log('PASS: '+name)};
const server=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8');
const sec=fs.readFileSync(path.join(root,'backend/src/security.js'),'utf8');
const srv=server+sec;
const env=fs.readFileSync(path.join(root,'backend/.env.example'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'backend/package.json'),'utf8'));
const migrations=fs.readdirSync(path.join(root,'database/migrations')).filter(x=>/^\d+_.*\.sql$/.test(x)).sort();
ok('runtime version V74',server.includes("version:'V74'")&&server.includes('API V74 running'));
ok('health and ready are public',server.includes("app.get('/health'")&&server.includes("app.get('/ready'"));
ok('production env validation',server.includes('validateProductionEnv'));
ok('security middleware present',srv.includes('helmet')&&srv.includes('rateLimit')&&srv.includes('cors'));
ok('JWT production secret validation',srv.includes('JWT_SECRET')&&srv.includes('32'));
ok('CORS allowlist',srv.includes('CORS_ORIGIN'));
ok('login rate limit',server.includes('loginLimiter'));
ok('request id/error handler',srv.includes('requestId')&&srv.includes('errorHandler'));
ok('migration chain present',migrations.some(x=>x.startsWith('025_')));
ok('backend start script',typeof pkg.scripts?.start==='string');
ok('backend env example has DB/JWT/CORS',env.includes('DATABASE_URL')&&env.includes('JWT_SECRET')&&env.includes('CORS_ORIGIN'));
console.log('V74 PREFLIGHT: 12/12 PASS');
