import fs from 'fs';
import path from 'path';
const root=process.cwd();
const server=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8');
const jsx=fs.readFileSync(path.join(root,'frontend/src/main.jsx'),'utf8');
const migDir=path.join(root,'database/migrations');
const migrations=fs.readdirSync(migDir).filter(x=>/^\d+_.*\.sql$/.test(x)).sort();
const checks=[]; const c=(n,ok)=>checks.push([n,!!ok]);
c('Migration files 006-024 present',Array.from({length:19},(_,i)=>String(i+6).padStart(3,'0')).every(n=>migrations.some(x=>x.startsWith(n+'_'))));
c('Operational integrity migration present',fs.existsSync(path.join(migDir,'024_operational_integrity.sql')));
c('Health endpoint reports V68',/version:'V68'/.test(server)&&/app\.get\('\/health'/.test(server));
c('Ready endpoint reports V68',/app\.get\('\/ready'/.test(server)&&/ready:true,version:'V68'/.test(server));
c('Startup banner V68',/Magra School API V68 running/.test(server));
c('JWT authentication',/jwt\.verify/.test(server));
c('RBAC',/allow\s*=|allow\(/.test(server));
c('Rate limits',/rateLimit|apiLimiter|loginLimiter/.test(server));
c('Helmet',/helmet\(/.test(server));
c('Logout',/auth\/logout/.test(server)&&/localStorage\.removeItem\('magra_token'\)/.test(jsx));
c('Public dropdown accessibility',/aria-expanded/.test(jsx)&&/aria-haspopup="menu"/.test(jsx));
c('Escape menu close',/e\.key==='Escape'/.test(jsx));
c('Outside click menu close',/pointerdown/.test(jsx)&&/closest\('\.reference-shell'\)/.test(jsx));
c('Student portal exists',/function StudentPortal/.test(jsx));
c('Guardian portal exists',/function GuardianPortal/.test(jsx));
c('Teacher portal exists',/function TeacherPortal/.test(jsx));
c('Assignment submission route',/assignments\/.*submit/.test(server)&&/submit/.test(jsx));
c('Scholarship workflow',/scholarships/.test(server)&&/ScholarshipPanel/.test(jsx));
c('Transport workflow',/transport\/vehicles/.test(server)&&/TransportPanel/.test(jsx));
c('Hostel workflow',/hostel\/rooms/.test(server)&&/HostelPanel/.test(jsx));
c('School EIIN 114290',/114290/.test(jsx));
c('Teacher learning ownership guard',/role_name==='teacher'/.test(server)&&/teaching assignment নেই/.test(server)&&/FROM routines WHERE teacher_id=\$1 AND class_name=\$2/.test(server));
c('Student learning feed',/data\.learning=/.test(server)&&/ডিজিটাল লার্নিং/.test(jsx));
c('Guardian performance summary',/guardianSummary/.test(server)&&/উপস্থিতি ও পারফরম্যান্স/.test(jsx));
c('Teacher marks and assignment tools',/portal\/teacher\/marks-roster/.test(server)&&/assignment-submissions/.test(server)&&/নম্বর এন্ট্রি/.test(jsx));
const pass=checks.filter(x=>x[1]).length; console.log(`V68 Final Audit: ${pass}/${checks.length} PASS`); for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'} | ${n}`); if(pass!==checks.length) process.exit(1);
