import fs from 'fs'; import path from 'path';
const root=process.cwd(); let pass=0,fail=0; const check=(n,o)=>{console.log(`${o?'PASS':'FAIL'}  ${n}`);o?pass++:fail++};
const s=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8');
const u=fs.readFileSync(path.join(root,'frontend/src/main.jsx'),'utf8');
const v=fs.readFileSync(path.join(root,'frontend/vite.config.js'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'frontend/package.json'),'utf8'));
check('guardian alerts use explicit guardian-student link',s.includes('guardian_student_links gsl ON gsl.student_id=s.id'));
check('guardian alert does not match phone as identity',!s.includes('g.phone=s.guardian_phone'));
check('routine PUT remains available',s.includes("app.put('/api/routines/:id'"));
check('routine edit state',u.includes('[editing,setEditing]'));
check('routine edit action',u.includes('function edit(r)'));
check('routine update button',u.includes("editing?'রুটিন আপডেট করুন':'রুটিন যোগ করুন'"));
check('routine cancel action',u.includes('editing&&<button className="mini"'));
check('routine delete action',u.includes('onClick={()=>remove(r.id)}'));
check('notifications admin role query uses roles table',s.includes('r.name role_name,r.label_bn'));
check('production auth token version check',s.includes('stale session'));
check('PWA plugin configured',v.includes('VitePWA') && pkg.dependencies['vite-plugin-pwa']);
check('PWA manifest and offline fallback',v.includes('navigateFallback') && v.includes('manifest:'));
check('install/offline UI wired',u.includes('beforeinstallprompt') && u.includes('offline-bar'));
console.log(`V24 static QA: ${pass}/${pass+fail} passed`); if(fail) process.exit(1);
