import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(); const checks=[];
const ok=(name,pass)=>checks.push({name,pass});
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const main=read('frontend/src/main.jsx'), nav=read('frontend/src/publicNavConfig.js'), css=read('frontend/src/styles.css'), server=read('backend/src/server.js');
ok('V61 reference images retained',fs.existsSync(path.join(root,'docs/ui-reference/reference-01-top.jpg'))&&fs.existsSync(path.join(root,'docs/ui-reference/reference-02-notice-links.jpg')));
ok('Header login action added',main.includes('className="header-login"'));
ok('Desktop nav login is not duplicated',css.includes('.reference-shell .nav-band .nav-login{display:none}'));
ok('Escape closes public navigation',main.includes("if(e.key==='Escape')closeNav()"));
ok('Dropdown exposes menu semantics',main.includes('aria-haspopup="menu"')&&main.includes('role="menu"'));
ok('Keyboard focus can open dropdown',css.includes('.reference-shell .nav-dropdown:focus-within>.nav-menu'));
ok('Mobile menu remains available',css.includes('.reference-shell .nav-toggle{display:block}'));
ok('Configured public menu remains source of truth',main.includes("publicNavConfig.map"));
ok('Correct school EIIN retained',main.includes('EIIN: <b>114290</b>')&&!main.includes('114282'));
ok('Header has reference-style topbar',main.includes('className="topbar"')&&main.includes('MPO: <b>4206071302</b>'));
ok('Backend health version V62',server.includes("version:'V62'"));
ok('No obsolete V61 health version remains',!server.includes("version:'V61'"));
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} | ${c.name}`);
const passed=checks.filter(x=>x.pass).length; console.log(`RESULT ${passed}/${checks.length}`); if(passed!==checks.length) process.exit(1);
