import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const checks=[];
const ok=(name,condition,detail='')=>checks.push({name,pass:Boolean(condition),detail});
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const seed=read('database/pilot/pilot_seed.sql');
const setup=read('scripts/pilot_setup.mjs');
const verify=read('scripts/pilot_verify.mjs');
const migrations=fs.readdirSync(path.join(root,'database/migrations')).filter(x=>/^\d+_.*\.sql$/.test(x)).sort((a,b)=>Number(a.slice(0,3))-Number(b.slice(0,3)));
ok('V85 release notes',fs.existsSync(path.join(root,'docs/V85-release-notes.md')));
ok('pilot setup guide',fs.existsSync(path.join(root,'docs/PILOT-SETUP-GUIDE.md')));
ok('pilot env template',fs.existsSync(path.join(root,'backend/.env.pilot.example')));
ok('portable setup uses pg Client',/new Client\(/.test(setup) && /from 'pg'/.test(setup));
ok('setup refuses production',/NODE_ENV === 'production'/.test(setup));
ok('setup applies schema and all migrations',/database\/schema\.sql/.test(setup) && /database\/migrations/.test(setup) && /database\/pilot\/pilot_seed\.sql/.test(setup));
ok('verification script exists',fs.existsSync(path.join(root,'scripts/pilot_verify.mjs')) && /PILOT VERIFY/.test(verify));
ok('all ten student accounts',Array.from({length:5},(_,i)=>['06','07','08','09','10'][i]).every(c=>seed.includes(`pilot-student-${c}-01`)&&seed.includes(`pilot-student-${c}-02`)));
ok('all ten student-user links',/SET user_id=u\.id/.test(seed) && /pilot-student-' \|\| replace/.test(seed));
ok('three teacher accounts',seed.includes('pilot-teacher-01')&&seed.includes('pilot-teacher-02')&&seed.includes('pilot-teacher-03'));
ok('two guardian accounts',seed.includes('pilot-guardian-01')&&seed.includes('pilot-guardian-02'));
ok('pilot password change flag',/must_change_password\)\s*SELECT/.test(seed) || /must_change_password\s*\).*TRUE/.test(seed));
ok('synthetic-only warning',/DO NOT use this file for production/.test(seed));
ok('production domain untouched',!/magrapalshs\.edu\.bd.*(renew|deploy|curl|wget|ssh)/is.test(setup+seed));
ok('migration 025 present',migrations.includes('025_document_integrity.sql'));
ok('migration sequence 006-025',JSON.stringify(migrations.map(x=>Number(x.slice(0,3))))===JSON.stringify(Array.from({length:20},(_,i)=>i+6)));
ok('pilot guide warns against production',/future production database|Never point `DATABASE_URL`/.test(read('docs/PILOT-SETUP-GUIDE.md')));
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} | ${c.name}${c.detail?` | ${c.detail}`:''}`);
const failed=checks.filter(c=>!c.pass).length;
console.log(`V85 QA: ${checks.length-failed}/${checks.length} PASS`);
process.exitCode=failed?1:0;
