import fs from 'node:fs';
const root=new URL('..',import.meta.url).pathname;
const read=p=>fs.readFileSync(root+p,'utf8');
const server=read('backend/src/server.js');
const ui=read('frontend/src/main.jsx');
const migration=read('database/migrations/024_operational_integrity.sql');
const checks=[];
const c=(name,ok)=>checks.push([name,!!ok]);
c('V71 health/ready version',/version:'V71'/.test(server)&&/ready:true,version:'V71'/.test(server));
c('V71 startup banner',/Magra School API V71 running/.test(server));
c('locked public reference nav retained',/Final reference-driven public navigation/.test(read('frontend/src/publicNavConfig.js')));
c('official school identity retained',/EIIN 114290/.test(ui)&&/মগড়া পালস্‌ ইউনিয়ন উচ্চ বিদ্যালয়/.test(ui));
c('leadership names retained',/নেয়ামুল হক খান/.test(ui)&&/মুহাম্মদ শফিকুল ইসলাম/.test(ui)&&/তাপসী সরকার/.test(ui));
c('document type coverage',/id_card/.test(ui)&&/marksheet/.test(ui)&&/progress_report/.test(ui)&&/certificate/.test(ui)&&/admit_card/.test(ui)&&/tabulation/.test(ui)&&/merit_list/.test(ui));
c('admit card requires selected exam',/type==='admit_card'\)\{/.test(server)&&/প্রবেশপত্রের জন্য পরীক্ষা নির্বাচন করুন/.test(server));
c('admit card returns exam details',/exam:ex\.rows\[0\]/.test(server));
c('tabulation/merit supports class selection',/const targetClass=className\|\|student\.class_name/.test(server)&&/classBased=\['tabulation','merit_list'\]/.test(ui));
c('tabulation/merit UI no longer requires student',/!classBased\.includes\(type\)&&<select value=\{studentId\}/.test(ui));
c('print template has dedicated admit card',/type==='admit_card'\)body=`<div class=\"doc admit\"/.test(ui));
c('student portal retained',/StudentPortal/.test(ui)&&/ডিজিটাল লার্নিং/.test(ui)&&/অনলাইন পরীক্ষা ও কুইজ/.test(ui));
c('teacher portal retained',/TeacherPortal/.test(ui)&&/দ্রুত উপস্থিতি/.test(ui)&&/নম্বর এন্ট্রি/.test(ui));
c('assignment evaluation retained',/assignment-submissions/.test(ui)&&/মূল্যায়ন/.test(ui));
c('operational integrity migration retained',/CREATE UNIQUE INDEX/.test(migration));
const pass=checks.filter(x=>x[1]).length;
console.log(`V71 Functional Completion Audit: ${pass}/${checks.length} PASS`);
for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'} | ${n}`);
if(pass!==checks.length) process.exit(1);
