import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(); const checks=[];
const ok=(name,pass)=>checks.push({name,pass});
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const main=read('frontend/src/main.jsx'), nav=read('frontend/src/publicNavConfig.js'), css=read('frontend/src/styles.css'), server=read('backend/src/server.js');
const ids=[...main.matchAll(/id=\"([^\"]+)\"/g)].map(m=>m[1]);
const hrefs=[...nav.matchAll(/href:'(#[-a-z]+)/g)].map(m=>m[1].slice(1));
ok('Home anchor exists',ids.includes('home'));
ok('Notice anchor exists',ids.includes('notice'));
ok('Gallery anchor exists',ids.includes('gallery'));
ok('Contact anchor exists',ids.includes('contact'));
ok('Reference submenu anchors are provisioned',hrefs.filter(x=>x!=='login').every(x=>ids.includes(x)));
ok('Reference menu config has dropdowns',nav.includes('children:['));
ok('Public navigation is data-driven',main.includes('publicNavConfig.map'));
ok('Seven-image layout remains unlocked',main.includes('public-anchor-shelf'));
ok('Header login remains unique',main.includes('className="header-login"')&&css.includes('.reference-shell .nav-band .nav-login{display:none}'));
ok('School EIIN is correct',main.includes('EIIN: <b>114290</b>')&&!main.includes('EIIN: <b>114282</b>'));
ok('Reference images retained',fs.existsSync(path.join(root,'docs/ui-reference/reference-01-top.jpg'))&&fs.existsSync(path.join(root,'docs/ui-reference/reference-02-notice-links.jpg')));
ok('Backend health version V63',server.includes("version:'V63'"));
const passed=checks.filter(x=>x.pass).length; for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} | ${c.name}`); console.log(`RESULT ${passed}/${checks.length}`); if(passed!==checks.length) process.exit(1);
