import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
let failed=0,checks=[];
const ok=(name,cond)=>{checks.push([name,!!cond]);if(!cond){failed++;console.log('FAIL |',name)}else console.log('PASS |',name)};
const main=read('frontend/src/main.jsx');
const css=read('frontend/src/styles.css');
const server=read('backend/src/server.js');
const mdir=path.join(root,'database','migrations');
const migrations=fs.readdirSync(mdir).filter(f=>/^\d+_.*\.sql$/.test(f)).sort((a,b)=>Number(a.slice(0,3))-Number(b.slice(0,3)));
const nums=migrations.map(x=>Number(x.slice(0,3)));
const expected=Array.from({length:22},(_,i)=>i+6);
ok('V88 release notes',fs.existsSync(path.join(root,'docs/V88-release-notes.md')));
ok('hierarchical navigation registry',fs.existsSync(path.join(mdir,'027_navigation_hierarchy.sql')));
ok('feature registry migration',fs.existsSync(path.join(mdir,'026_feature_registry.sql')));
ok('migration sequence 006-027',JSON.stringify(nums)===JSON.stringify(expected));
ok('Feature Control panel',/function FeatureControlPanel\(\)/.test(main));
ok('Admin hierarchical navigation',/const ADMIN_NAV_GROUPS=/.test(main)&&/side-subnav/.test(main));
ok('marks entry submenu',/admin\.results\.marks/.test(read('database/migrations/027_navigation_hierarchy.sql')));
ok('marksheet/tabulation/merit submenus',/admin\.results\.marksheet/.test(read('database/migrations/027_navigation_hierarchy.sql'))&&/admin\.results\.tabulation/.test(read('database/migrations/027_navigation_hierarchy.sql'))&&/admin\.results\.merit/.test(read('database/migrations/027_navigation_hierarchy.sql')));
ok('public menu submenu registry',/public\.nav\.institution\.about/.test(read('database/migrations/027_navigation_hierarchy.sql')));
ok('custom feature API',/\/api\/admin\/custom-features/.test(server));
ok('custom feature URL validation',server.includes('Target URL')&&server.includes('https:\\/\\/'));
ok('modern student form',/STUDENT MANAGEMENT/.test(main)&&/step-tabs/.test(main));
ok('modern teacher/staff form',/STAFF MANAGEMENT/.test(main)&&/step-tabs/.test(main));
ok('custom feature styling',/\.feature-control/.test(css)&&/\.step-tabs/.test(css));
ok('login role routing fixed',main.includes("d.user.role)?'/portal':'/admin'"));
ok('pilot setup applies every migration',read('scripts/pilot_setup.mjs').includes('.filter((f) => /^\\d+_.*\\.sql$/.test(f))'));
console.log(`V88 QA: ${checks.length-failed}/${checks.length} PASS`);
if(failed)process.exit(1);
