import fs from 'fs';
import path from 'path';
const root=process.cwd();
const server=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8');
const jsx=fs.readFileSync(path.join(root,'frontend/src/main.jsx'),'utf8');
const nav=fs.readFileSync(path.join(root,'frontend/src/publicNavConfig.js'),'utf8');
const css=fs.readFileSync(path.join(root,'frontend/src/styles.css'),'utf8');
const checks=[]; const c=(n,ok)=>checks.push([n,!!ok]);
c('Migrations 006-024 present',Array.from({length:19},(_,i)=>String(i+6).padStart(3,'0')).every(n=>fs.readdirSync(path.join(root,'database/migrations')).some(x=>x.startsWith(n+'_'))));
c('V70 health/ready',/version:'V70'/.test(server)&&/ready:true,version:'V70'/.test(server));
c('V70 startup banner',/Magra School API V70 running/.test(server));
c('Final 1→2→3→4 reference navigation lock',/original 7 screenshots.*4 final reference sections/.test(nav));
c('Reference hero/service/notice/link blocks',/ref-hero/.test(jsx)&&/service-grid/.test(jsx)&&/নোটিশবোর্ড/.test(jsx)&&/গুরুত্বপূর্ণ লিংকসমূহ/.test(jsx));
c('Reference 3/4 continuation blocks',/বিদ্যালয় সম্পর্কে/.test(jsx)&&/শিক্ষকবৃন্দ/.test(jsx)&&/কৃতি শিক্ষার্থী/.test(jsx)&&/ফটো ও ভিডিও গ্যালারি/.test(jsx));
c('Leadership names exact',/নেয়ামুল হক খান/.test(jsx)&&/মুহাম্মদ শফিকুল ইসলাম/.test(jsx)&&/তাপসী সরকার/.test(jsx));
c('School identity exact',/114290/.test(jsx)&&/magrapuhs.46@gmail.com/.test(jsx)&&/১৯৪৬/.test(jsx));
c('Official education links wired',/https:\/\/moedu.gov.bd/.test(jsx)&&/https:\/\/dshe.gov.bd/.test(jsx)&&/https:\/\/www.dhakaeducationboard.gov.bd/.test(jsx));
c('External links safe',/target="_blank" rel="noopener noreferrer"/.test(jsx));
c('Home gallery lightbox',/ref-lightbox/.test(jsx)&&/aria-modal="true"/.test(jsx));
c('Public content lightbox retained',/className="lightbox"/.test(jsx)&&/setLightbox/.test(jsx));
c('Responsive layout',/@media\(max-width:650px\)/.test(css)&&/service-grid\{grid-template-columns:repeat\(2,1fr\)/.test(css));
c('Dropdown accessibility',/aria-expanded/.test(jsx)&&/aria-haspopup="menu"/.test(jsx));
c('Login/PWA retained',/function Login\(\)/.test(jsx)&&/function PWAStatus\(\)/.test(jsx));
const pass=checks.filter(x=>x[1]).length; console.log(`V70 Final View Audit: ${pass}/${checks.length} PASS`); for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'} | ${n}`); if(pass!==checks.length) process.exit(1);
