import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(); const checks=[];
const ok=(name,pass)=>checks.push({name,pass});
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const sql=read('database/migrations/024_operational_integrity.sql');
const server=read('backend/src/server.js');
const nav=read('frontend/src/publicNavConfig.js');
const main=read('frontend/src/main.jsx');
const css=read('frontend/src/styles.css');
const migrations=fs.readdirSync(path.join(root,'database/migrations')).filter(x=>/^\d+_.*\.sql$/.test(x)).sort();
ok('Migration 024 exists and is ordered after 023',migrations.indexOf('023_assignment_feedback.sql')<migrations.indexOf('024_operational_integrity.sql'));
ok('Transport active student uniqueness',sql.includes('uq_transport_active_student')&&sql.includes("ON transport_assignments(student_id) WHERE status='active'"));
ok('Hostel active student uniqueness',sql.includes('uq_hostel_active_student')&&sql.includes("ON hostel_assignments(student_id) WHERE status='active'"));
ok('Hostel active bed uniqueness',sql.includes('uq_hostel_active_bed')&&sql.includes('room_id,bed_no'));
ok('Duplicate active assignments are safely deactivated before indexes',sql.includes('ROW_NUMBER() OVER (PARTITION BY student_id')&&sql.includes("SET status='inactive'"));
ok('Public content index added',sql.includes('idx_school_content_public'));
ok('API health reports V65',server.includes("version:'V65'"));
ok('API ready reports V65',server.includes("res.json({ok:true,ready:true,version:'V65'})"));
ok('Server startup label reports V65',server.includes('Magra School API V65 running'));
ok('Public navigation remains data-driven',main.includes('publicNavConfig.map'));
ok('Reference menu config retained',nav.includes('প্রাতিষ্ঠানিক তথ্য')&&nav.includes('ক্রীড়া ও সংস্কৃতি')&&nav.includes('শিক্ষার্থীর গাইড'));
ok('Responsive navigation CSS retained',css.includes('.reference-shell .nav-toggle')&&css.includes('.reference-shell .nav-band nav.open'));
ok('No stale V64 health version',!server.includes("version:'V64'"));
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} | ${c.name}`);
const passed=checks.filter(x=>x.pass).length; console.log(`RESULT ${passed}/${checks.length}`); if(passed!==checks.length) process.exit(1);
