import fs from 'fs'; import path from 'path';
const root=process.cwd(), server=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8'), jsx=fs.readFileSync(path.join(root,'frontend/src/main.jsx'),'utf8');
const schema=fs.readFileSync(path.join(root,'database/schema.sql'),'utf8');
const m024=fs.readFileSync(path.join(root,'database/migrations/024_operational_integrity.sql'),'utf8');
const checks=[]; const c=(n,ok)=>checks.push([n,!!ok]);
c('Migration 024 present',fs.existsSync(path.join(root,'database/migrations/024_operational_integrity.sql')));
c('created_by columns use UUID in schema',/created_by\s+UUID\b/i.test(schema));
c('Transport active-student unique index',/uq_transport_active_student[\s\S]{0,180}WHERE status='active'/i.test(m024));
c('Hostel active-student unique index',/uq_hostel_active_student[\s\S]{0,180}WHERE status='active'/i.test(m024));
c('Hostel active-bed unique index',/uq_hostel_active_bed[\s\S]{0,180}WHERE status='active'/i.test(m024));
c('Scholarship API',/scholarships/i.test(server)); c('Events API',/event_participants|\/events/i.test(server));
c('Assignment submit flow',/assignments\/\$\{a\.id\}\/submit/.test(jsx)&&/assignments\/.*submit/.test(server));
c('Notification read-all',/notifications\/read-all/.test(jsx)&&/notifications\/read-all/.test(server));
c('Production env validation',/validateProductionEnv/.test(server)); c('Rate limiting',/rateLimit|apiLimiter|loginLimiter/.test(server));
c('Helmet security headers',/helmet\(/.test(server)); c('JWT verification',/jwt\.verify/.test(server)); c('RBAC middleware',/allow\s*=|allow\(/.test(server));
c('Logout endpoint',/auth\/logout/.test(server));
c('Desktop/mobile dropdown accessibility',/aria-expanded/.test(jsx)&&/nav-toggle/.test(jsx));
c('Outside-click menu close',/pointerdown/.test(jsx)&&/closest\('\.reference-shell'\)/.test(jsx));
c('Escape closes menu',/e\.key==='Escape'/.test(jsx));
c('School EIIN 114290',/114290/.test(jsx));
const pass=checks.filter(x=>x[1]).length; console.log(`V66 Final Audit: ${pass}/${checks.length} PASS`); for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'} | ${n}`); if(pass!==checks.length) process.exit(1);
