import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const ok=(name,cond)=>{if(!cond)throw new Error('FAIL: '+name);console.log('PASS: '+name)};
const server=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8');
const jsx=fs.readFileSync(path.join(root,'frontend/src/main.jsx'),'utf8');
const mig=fs.readdirSync(path.join(root,'database/migrations')).filter(x=>/^0\d+_.*\.sql$/.test(x)).sort();
ok('migrations through 025',mig.some(x=>x.startsWith('025_')));
ok('password reset endpoint',server.includes("app.post('/api/users/:id/reset-password'"));
ok('reset invalidates sessions',server.includes('auth_token_version=auth_token_version+1')&&server.includes('must_change_password=true'));
ok('users UI exposes password reset',jsx.includes("/users/'+u.id+'/reset-password")&&jsx.includes('Password Reset'));
ok('users UI can assign all non-super roles',jsx.includes('roleOptions')&&jsx.includes("head_teacher")&&jsx.includes("guardian"));
ok('super admin protected in UI',jsx.includes("u.role_name==='super_admin'"));
ok('final reference navigation retained',jsx.includes('Final reference-driven public navigation')||fs.readFileSync(path.join(root,'frontend/src/publicNavConfig.js'),'utf8').includes('Final reference-driven public navigation'));
ok('EIIN 114290 retained',jsx.includes('EIIN 114290')||server.includes('114290'));
ok('official document module retained',jsx.includes('Official Document Generator')&&jsx.includes('Officially Issue'));
ok('student portal retained',jsx.includes('function StudentPortal'));
ok('guardian portal retained',jsx.includes('function GuardianPortal'));
ok('teacher portal retained',jsx.includes('function TeacherPortal'));
console.log('V73 QA: 11/11 PASS');
