import fs from 'fs';
import path from 'path';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const checks=[];
const ok=(name,cond,detail='')=>checks.push({name,pass:Boolean(cond),detail});
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const server=read('backend/src/server.js');
const pkg=JSON.parse(read('frontend/package.json'));
ok('Backend reports V78', server.includes("version:'V78'"));
ok('Ready endpoint reports V78', server.includes("res.json({ok:true,ready:true,version:'V78'})"));
ok('Unready endpoint reports V78', server.includes("res.status(503).json({ok:false,ready:false,version:'V78'})"));
ok('Live readiness uses PostgreSQL SELECT 1', /pool\.query\(['"]SELECT 1['"]\)/.test(server));
ok('Production build script exists', pkg.scripts?.build==='vite build');
ok('React/Vite dependencies present', Boolean(pkg.dependencies?.react && pkg.dependencies?.vite));
const migrations=fs.readdirSync(path.join(root,'database/migrations')).filter(x=>x.endsWith('.sql')).sort();
ok('Migration set exists', migrations.length>=20, `${migrations.length} migrations`);
ok('Document integrity migration retained', migrations.some(x=>x.includes('025')) || read('database/migrations/025_document_integrity.sql').length>0);
ok('Final public reference lock retained', read('frontend/src/publicNavConfig.js').includes('1→2→3→4') || read('frontend/src/publicNavConfig.js').includes('1->2->3->4'));
ok('School EIIN retained', server.includes('114290') || read('frontend/src/main.jsx').includes('114290'));
ok('Production env validator retained', server.includes('validateProductionEnv'));
ok('JWT auth retained', server.includes('jsonwebtoken') || server.includes('jwt'));
ok('Rate limiting retained', server.includes('rateLimit'));
ok('Helmet retained', server.includes('helmet'));
const qa=checks.filter(x=>x.pass).length;
console.log(`V78 QA: ${qa}/${checks.length} PASS`);
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} - ${c.name}${c.detail?' :: '+c.detail:''}`);
if(qa!==checks.length) process.exit(1);
