import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const checks=[];
const ok=(name,fn)=>{try{if(!fn())throw new Error('fail');checks.push([name,'PASS'])}catch(e){checks.push([name,'FAIL'])}};
const read=(f)=>fs.readFileSync(path.join(root,f),'utf8');
ok('V83 backend markers',()=>read('backend/src/server.js').includes("version:'V83'")&&read('backend/src/server.js').includes('Magra School API V83 running'));
ok('Pilot plan',()=>fs.existsSync(path.join(root,'docs/PILOT-TEST-PLAN.md')));
ok('Pilot DB options',()=>fs.existsSync(path.join(root,'docs/PILOT-DATABASE-OPTIONS.md')));
ok('Teacher CSV template',()=>read('docs/pilot-data/teachers-template.csv').includes('employee_id,name_bn'));
ok('Student CSV template',()=>read('docs/pilot-data/students-template.csv').includes('student_id,roll_no'));
ok('No production domain in pilot config',()=>!read('docs/PILOT-TEST-PLAN.md').includes('https://magrapalshs.edu.bd'));
ok('View page lock retained',()=>read('frontend/src/publicNavConfig.js').includes('Final reference-driven public navigation'));
ok('School EIIN retained',()=>read('frontend/src/main.jsx').includes('114290')||read('backend/src/server.js').includes('114290'));
ok('PWA login route retained',()=>read('frontend/src/main.jsx').includes('location.pathname==="/login"'));
ok('Production env remains configurable',()=>read('backend/.env.example').includes('DATABASE_URL')&&read('backend/.env.example').includes('JWT_SECRET'));
for(const [n,s] of checks) console.log(`${s==='PASS'?'✓':'✗'} ${n}`);
console.log(`V83 QA: ${checks.filter(x=>x[1]==='PASS').length}/${checks.length} PASS`);
if(checks.some(x=>x[1]==='FAIL'))process.exit(1);
