import fs from 'fs';
const root = new URL('..', import.meta.url).pathname;
const read = (p) => fs.readFileSync(new URL(p, import.meta.url), 'utf8');
const checks = [];
const main = read('../frontend/src/main.jsx');
const css = read('../frontend/src/styles.css');
const vite = read('../frontend/vite.config.js');
const server = read('../backend/src/server.js');
const add = (name, ok) => { checks.push([name, !!ok]); console.log(`${ok?'PASS':'FAIL'} ${name}`); };
add('Dedicated /login route exists', main.includes('location.pathname==="/login"'));
add('Header login navigates to /login', main.includes('href="/login"'));
add('Login loading state', main.includes('লগইন হচ্ছে'));
add('Login button disabled while loading', main.includes('disabled={loading}'));
add('Login status aria-live', main.includes('aria-live'));
add('Password visibility control retained', main.includes('[show,setShow]'));
add('Password reset guidance retained', main.includes('পাসওয়ার্ড ভুলে গেলে') && main.includes('Password reset'));
add('Back-to-site link', main.includes('মূল ওয়েবসাইট'));
add('Final 1→2→3→4 public structure retained', main.includes('ref-hero') && main.includes('ref-main') && main.includes('ref-bottom'));
add('EIIN 114290 retained', main.includes('114290'));
add('School logo retained', fs.existsSync(new URL('../frontend/public/school-logo.png', import.meta.url)));
add('School building retained', fs.existsSync(new URL('../frontend/public/school-building.jpg', import.meta.url)));
add('V82 backend version', server.includes("version:'V82'") && server.includes('Magra School API V82'));
add('Login action styling', css.includes('.login-submit'));
add('Disabled login styling', css.includes('.login-submit:disabled'));
add('Mobile login shell retained', css.includes('.login-shell') && css.includes('.loginbox-modern') && css.includes('@media'));
add('PWA Login shortcut uses /login route', vite.includes("url: '/login'"));
add('PWA fallback remains configured', vite.includes("navigateFallback: '/index.html'"));
add('PWA school assets retained', vite.includes("school-logo.png") && vite.includes("school-building.jpg"));
const fails = checks.filter(([,ok])=>!ok);
console.log(`RESULT ${checks.length-fails.length}/${checks.length}`);
if (fails.length) process.exit(1);
