import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(); const checks=[];
const ok=(name,pass,detail='')=>checks.push({name,pass,detail});
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const main=read('frontend/src/main.jsx'), nav=read('frontend/src/publicNavConfig.js'), css=read('frontend/src/styles.css'), server=read('backend/src/server.js');
ok('Reference image 01 exists',fs.existsSync(path.join(root,'docs/ui-reference/reference-01-top.jpg')));
ok('Reference image 02 exists',fs.existsSync(path.join(root,'docs/ui-reference/reference-02-notice-links.jpg')));
ok('Header imports public navigation config',main.includes("import {publicNavConfig} from './publicNavConfig';"));
ok('Header renders configured menu items',main.includes('publicNavConfig.map'));
ok('Dropdown trigger uses aria-expanded',main.includes('aria-expanded={dropdown===i}'));
ok('Desktop dropdown CSS exists',css.includes('.reference-shell .nav-dropdown:hover>.nav-menu'));
ok('Mobile navigation CSS exists',css.includes('.reference-shell .nav-band nav.open'));
ok('Institutional submenu exists',nav.includes('প্রাতিষ্ঠানিক তথ্য'));
ok('Student guide submenu exists',nav.includes('শিক্ষার্থীর গাইড'));
ok('Login remains explicit',nav.includes("label:'লগইন'"));
ok('Correct school EIIN retained',main.includes('EIIN 114290') && !main.includes('114282'));
ok('Backend version V61',server.includes("version:'V61'"));
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'} | ${c.name}${c.detail?' | '+c.detail:''}`);
const passed=checks.filter(x=>x.pass).length; console.log(`RESULT ${passed}/${checks.length}`); if(passed!==checks.length) process.exit(1);
