import fs from 'fs';
import path from 'path';
const root=process.cwd();
const server=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8');
const jsx=fs.readFileSync(path.join(root,'frontend/src/main.jsx'),'utf8');
const css=fs.readFileSync(path.join(root,'frontend/src/styles.css'),'utf8');
const checks=[]; const c=(n,ok)=>checks.push([n,!!ok]);
c('Migrations 006-024 present',Array.from({length:19},(_,i)=>String(i+6).padStart(3,'0')).every(n=>fs.readdirSync(path.join(root,'database/migrations')).some(x=>x.startsWith(n+'_'))));
c('V69 health/ready',/version:'V69'/.test(server)&&/ready:true,version:'V69'/.test(server));
c('V69 startup banner',/Magra School API V69 running/.test(server));
c('Reference 1 hero and ticker',/ref-hero/.test(jsx)&&/ref-ticker/.test(jsx));
c('Reference 1 service grid',/আমাদের বিভিন্ন শিক্ষা কার্যক্রম/.test(jsx)&&/service-grid/.test(jsx));
c('Reference 2 notice board',/নোটিশবোর্ড/.test(jsx)&&/notice-table/.test(jsx));
c('Reference 2 three link panels',/গুরুত্বপূর্ণ লিংকসমূহ/.test(jsx)&&/শিক্ষা বোর্ডসমূহ/.test(jsx)&&/বোর্ড গুরুত্বপূর্ণ লিংকসমূহ/.test(jsx));
c('Reference 3 service continuation',/অনলাইন পরীক্ষা/.test(jsx)&&/ডিজিটাল শিক্ষা/.test(jsx)&&/বৃত্তি ও অর্জন/.test(jsx));
c('Reference 4 school info/teachers/distinguished/gallery',/বিদ্যালয় সম্পর্কে/.test(jsx)&&/শিক্ষকবৃন্দ/.test(jsx)&&/কৃতি শিক্ষার্থী/.test(jsx)&&/ফটো ও ভিডিও গ্যালারি/.test(jsx));
c('Leadership names exact',/নেয়ামুল হক খান/.test(jsx)&&/মুহাম্মদ শফিকুল ইসলাম/.test(jsx)&&/তাপসী সরকার/.test(jsx));
c('School EIIN exact',/114290/.test(jsx));
c('School logo and building assets',/school-logo\.png/.test(jsx)&&/school-building\.jpg/.test(jsx));
c('Responsive reference layout',/@media\(max-width:650px\)/.test(css)&&/service-grid\{grid-template-columns:repeat\(2,1fr\)/.test(css));
c('Public dropdown accessibility retained',/aria-expanded/.test(jsx)&&/aria-haspopup="menu"/.test(jsx));
c('Login component retained',/function Login\(\)/.test(jsx)&&/auth\/login/.test(jsx));
c('PWA status retained',/function PWAStatus\(\)/.test(jsx));
const pass=checks.filter(x=>x[1]).length; console.log(`V69 Reference View Audit: ${pass}/${checks.length} PASS`); for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'} | ${n}`); if(pass!==checks.length) process.exit(1);
