import fs from 'node:fs';
const root=new URL('..',import.meta.url).pathname;
const read=p=>fs.readFileSync(root+p,'utf8');
const server=read('backend/src/server.js');
const ui=read('frontend/src/main.jsx');
const migration=read('database/migrations/025_document_integrity.sql');
const checks=[];
const c=(name,ok)=>checks.push([name,!!ok]);
c('V72 health/ready/startup version',/version:'V72'/.test(server)&&/Magra School API V72 running/.test(server));
c('document type allowlist in preview API',/documentTypes=new Set\(\['id_card','marksheet','progress_report','certificate','admit_card','tabulation','merit_list'\]\)/.test(server));
c('document issue type validation',/অবৈধ ডকুমেন্ট ধরন/.test(server)&&/documentTypes=\['id_card','marksheet','progress_report','certificate','admit_card','tabulation','merit_list'\]/.test(server));
c('student requirement enforced for individual documents',/এই ডকুমেন্টের জন্য শিক্ষার্থী নির্বাচন করুন/.test(server));
c('exam requirement enforced for exam documents',/এই ডকুমেন্টের জন্য পরীক্ষা নির্বাচন করুন/.test(server));
c('issued document integrity migration',/issued_documents_document_type_check/.test(migration)&&/CREATE INDEX IF NOT EXISTS idx_issued_documents_exam/.test(migration));
c('official issue UI retained',/Officially Issue/.test(ui)&&/\/documents\/issue/.test(ui));
c('issued registry displayed',/ইস্যু করা ডকুমেন্ট/.test(ui)&&/\/documents\/issued/.test(ui));
c('print HTML escaping helper',/function escapeHtml\(value\)/.test(ui)&&/esc\(student\.name_bn\)/.test(ui)&&/esc\(school\.nameBn\)/.test(ui));
c('print window includes UTF-8 metadata',/meta charset="utf-8"/.test(ui));
c('locked public reference retained',/Final reference-driven public navigation/.test(read('frontend/src/publicNavConfig.js')));
c('school identity retained',/EIIN 114290/.test(ui)&&/মগড়া পালস্‌ ইউনিয়ন উচ্চ বিদ্যালয়/.test(ui));
c('leadership names retained',/নেয়ামুল হক খান/.test(ui)&&/মুহাম্মদ শফিকুল ইসলাম/.test(ui)&&/তাপসী সরকার/.test(ui)&&/মুহাম্মদ আবুবকর সিদ্দিক/.test(ui));
c('V71 document coverage retained',/admit_card/.test(ui)&&/tabulation/.test(ui)&&/merit_list/.test(ui));
c('portal workflows retained',/StudentPortal/.test(ui)&&/TeacherPortal/.test(ui)&&/GuardianPortal/.test(ui));
const pass=checks.filter(x=>x[1]).length;
console.log(`V72 Document & Integrity Audit: ${pass}/${checks.length} PASS`);
for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'} | ${n}`);
if(pass!==checks.length) process.exit(1);
