import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const ok=(name,cond)=>{if(!cond)throw new Error('FAIL: '+name);console.log('PASS: '+name)};
const s=fs.readFileSync(path.join(root,'backend/src/server.js'),'utf8');
const sec=fs.readFileSync(path.join(root,'backend/src/security.js'),'utf8');
const jsx=fs.readFileSync(path.join(root,'frontend/src/main.jsx'),'utf8');
ok('bcrypt password hashing',s.includes('bcrypt.hash')&&s.includes('bcrypt.compare'));
ok('JWT auth verification',s.includes('jwt.verify'));
ok('inactive users blocked',s.includes('is_active=true'));
ok('session invalidation',s.includes('auth_token_version'));
ok('audit logging',s.includes('audit('));
ok('JSON body limit',s.includes("limit: '1mb'"));
ok('helmet',s.includes('helmet'));
ok('CORS configured',s.includes('cors'));
ok('API rate limit',s.includes('rateLimit'));
ok('login rate limit',s.includes('loginLimiter'));
ok('admin reset session invalidation',s.includes('reset-password')&&s.includes('must_change_password=true')&&s.includes('auth_token_version=auth_token_version+1'));
ok('super-admin protection',s.includes("role_name==='super_admin' && req.user.role!=='super_admin'")||s.includes('Super Admin'));
ok('external links noopener',jsx.includes('noopener noreferrer'));
console.log('V74 SECURITY AUDIT: 13/13 PASS');
